// Maps tool slug → G2 reviews page URL
// Used in ToolCard, ToolPage and ComparisonPage instead of hardcoded ratings

const g2Urls = {
  "hubspot-crm":        "https://www.g2.com/products/hubspot-crm/reviews",
  "apollo-io":          "https://www.g2.com/products/apollo-io/reviews",
  "lavender":           "https://www.g2.com/products/lavender/reviews",
  "fathom-ai":          "https://www.g2.com/products/fathom/reviews",
  "jasper":             "https://www.g2.com/products/jasper-ai/reviews",
  "copy-ai":            "https://www.g2.com/products/copy-ai/reviews",
  "canva-ai":           "https://www.g2.com/products/canva/reviews",
  "quickbooks":         "https://www.g2.com/products/quickbooks-online/reviews",
  "xero":               "https://www.g2.com/products/xero/reviews",
  "freshbooks":         "https://www.g2.com/products/freshbooks/reviews",
  "dext":               "https://www.g2.com/products/dext/reviews",
  "notion-ai":          "https://www.g2.com/products/notion/reviews",
  "clickup-ai":         "https://www.g2.com/products/clickup/reviews",
  "fireflies-ai":       "https://www.g2.com/products/fireflies-ai/reviews",
  "reclaim-ai":         "https://www.g2.com/products/reclaim-ai/reviews",
  "deel":               "https://www.g2.com/products/deel/reviews",
  "oyster-hr":          "https://www.g2.com/products/oyster-hr/reviews",
  "bamboohr":           "https://www.g2.com/products/bamboohr/reviews",
  "tidio":              "https://www.g2.com/products/tidio/reviews",
  "crisp":              "https://www.g2.com/products/crisp/reviews",
  "zendesk-smb":        "https://www.g2.com/products/zendesk-support/reviews",
  "zapier":             "https://www.g2.com/products/zapier/reviews",
  "make":               "https://www.g2.com/products/make-formerly-integromat/reviews",
  "pabbly-connect":     "https://www.g2.com/products/pabbly-connect/reviews",
  "adobe-express":      "https://www.g2.com/products/adobe-express/reviews",
  "visme":              "https://www.g2.com/products/visme/reviews",
  "looka":              "https://www.g2.com/products/looka/reviews",
  "plausible":          "https://www.g2.com/products/plausible-analytics/reviews",
  "looker-studio":      "https://www.g2.com/products/looker-studio/reviews",
  "mixpanel":           "https://www.g2.com/products/mixpanel/reviews",
  "seedlegals":         "https://www.g2.com/products/seedlegals/reviews",
  "docusign":           "https://www.g2.com/products/docusign/reviews",
  "legalzoom":          "https://www.g2.com/products/legalzoom/reviews",
  "writesonic":         "https://www.g2.com/products/writesonic/reviews",
  "grammarly-business": "https://www.g2.com/products/grammarly-business/reviews",
  "surfer-seo":         "https://www.g2.com/products/surfer-seo/reviews",
  "supabase":           "https://www.g2.com/products/supabase/reviews",
  "vercel":             "https://www.g2.com/products/vercel/reviews",
  "github":             "https://www.g2.com/products/github/reviews",
  "cloudflare":         "https://www.g2.com/products/cloudflare/reviews",
  "bubble":             "https://www.g2.com/products/bubble/reviews",
  "retool":             "https://www.g2.com/products/retool/reviews",
  "replit":             "https://www.g2.com/products/replit/reviews",
  "lovable":            "https://www.g2.com/products/lovable/reviews",
  "base44":             "https://www.g2.com/products/base44/reviews",
  "cursor":             "https://www.g2.com/products/cursor/reviews",
  "railway":            "https://www.g2.com/products/railway/reviews",
  "airtable":           "https://www.g2.com/products/airtable/reviews",
  "webflow":            "https://www.g2.com/products/webflow/reviews",
  "n8n":                "https://www.g2.com/products/n8n/reviews",
};

export default g2Urls;
